// generated by stringer -type=Type,Share -output=stringer_autogen.go; DO NOT EDIT

package game

import "fmt"

const _Type_name = "HoldemOmahaHiOmahaHiLoRazzStudHiStudHiLo"

var _Type_index = [...]uint8{6, 13, 22, 26, 32, 40}

func (i Type) String() string {
	i -= 1
	if i < 0 || i >= Type(len(_Type_index)) {
		return fmt.Sprintf("Type(%d)", i+1)
	}
	hi := _Type_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _Type_index[i-1]
	}
	return _Type_name[lo:hi]
}

const _Share_name = "WonHighWonLowSplitHighSplitLow"

var _Share_index = [...]uint8{7, 13, 22, 30}

func (i Share) String() string {
	i -= 1
	if i < 0 || i >= Share(len(_Share_index)) {
		return fmt.Sprintf("Share(%d)", i+1)
	}
	hi := _Share_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _Share_index[i-1]
	}
	return _Share_name[lo:hi]
}
