// generated by stringer -type=Ranking,Sorting,Ordering -output=stringer_autogen.go; DO NOT EDIT

package hand

import "fmt"

const _Ranking_name = "HighCardPairTwoPairThreeOfAKindStraightFlushFullHouseFourOfAKindStraightFlushRoyalFlush"

var _Ranking_index = [...]uint8{8, 12, 19, 31, 39, 44, 53, 64, 77, 87}

func (i Ranking) String() string {
	if i < 0 || i >= Ranking(len(_Ranking_index)) {
		return fmt.Sprintf("Ranking(%d)", i)
	}
	hi := _Ranking_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _Ranking_index[i-1]
	}
	return _Ranking_name[lo:hi]
}

const _Sorting_name = "SortingHighSortingLow"

var _Sorting_index = [...]uint8{11, 21}

func (i Sorting) String() string {
	i -= 1
	if i < 0 || i >= Sorting(len(_Sorting_index)) {
		return fmt.Sprintf("Sorting(%d)", i+1)
	}
	hi := _Sorting_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _Sorting_index[i-1]
	}
	return _Sorting_name[lo:hi]
}

const _Ordering_name = "ASCDESC"

var _Ordering_index = [...]uint8{3, 7}

func (i Ordering) String() string {
	i -= 1
	if i < 0 || i >= Ordering(len(_Ordering_index)) {
		return fmt.Sprintf("Ordering(%d)", i+1)
	}
	hi := _Ordering_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _Ordering_index[i-1]
	}
	return _Ordering_name[lo:hi]
}
