// Code generated by "stringer -type=Status,Round,Variant,Limit,ActionType"; DO NOT EDIT.

package table

import "strconv"

const _Status_name = "BrokenDealing"

var _Status_index = [...]uint8{0, 6, 13}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}

const _Round_name = "PreFlopFlopTurnRiver"

var _Round_index = [...]uint8{0, 7, 11, 15, 20}

func (i Round) String() string {
	if i < 0 || i >= Round(len(_Round_index)-1) {
		return "Round(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Round_name[_Round_index[i]:_Round_index[i+1]]
}

const _Variant_name = "TexasHoldemOmahaHi"

var _Variant_index = [...]uint8{0, 11, 18}

func (i Variant) String() string {
	if i < 0 || i >= Variant(len(_Variant_index)-1) {
		return "Variant(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Variant_name[_Variant_index[i]:_Variant_index[i+1]]
}

const _Limit_name = "NoLimitPotLimit"

var _Limit_index = [...]uint8{0, 7, 15}

func (i Limit) String() string {
	if i < 0 || i >= Limit(len(_Limit_index)-1) {
		return "Limit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Limit_name[_Limit_index[i]:_Limit_index[i+1]]
}

const _ActionType_name = "FoldCheckCallBetRaiseAllIn"

var _ActionType_index = [...]uint8{0, 4, 9, 13, 16, 21, 26}

func (i ActionType) String() string {
	if i < 0 || i >= ActionType(len(_ActionType_index)-1) {
		return "ActionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActionType_name[_ActionType_index[i]:_ActionType_index[i+1]]
}
