// generated by stringer -type=Game,ErrorType,PotShare -output=stringer_autogen.go; DO NOT EDIT

package table

import "fmt"

const _Game_name = "HoldemOmahaHiOmahaHiLoRazzStudHiStudHiLo"

var _Game_index = [...]uint8{6, 13, 22, 26, 32, 40}

func (i Game) String() string {
	i -= 1
	if i < 0 || i >= Game(len(_Game_index)) {
		return fmt.Sprintf("Game(%d)", i+1)
	}
	hi := _Game_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _Game_index[i-1]
	}
	return _Game_name[lo:hi]
}
