// generated by stringer -type=Game,ErrorType,PotShare -output=stringer_autogen.go; DO NOT EDIT

package table

import "fmt"

const _Game_name = "HoldemOmahaHiOmahaHiLoRazzStudHiStudHiLo"

var _Game_index = [...]uint8{6, 13, 22, 26, 32, 40}

func (i Game) String() string {
	i -= 1
	if i < 0 || i >= Game(len(_Game_index)) {
		return fmt.Sprintf("Game(%d)", i+1)
	}
	hi := _Game_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _Game_index[i-1]
	}
	return _Game_name[lo:hi]
}

const _ErrorType_name = "InvalidBuyInSeatOccupiedInvalidSeatAlreadySeatedInsufficientPlayersInvalidBetInvalidRaiseInvalidAction"

var _ErrorType_index = [...]uint8{12, 24, 35, 48, 67, 77, 89, 102}

func (i ErrorType) String() string {
	i -= 1
	if i < 0 || i >= ErrorType(len(_ErrorType_index)) {
		return fmt.Sprintf("ErrorType(%d)", i+1)
	}
	hi := _ErrorType_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _ErrorType_index[i-1]
	}
	return _ErrorType_name[lo:hi]
}
